/**
 * Created by Aleksey Chichenkov <cublakhan257@gmail.com> on 8/31/20.
 */

export default {
  digits: [
    0, 1, 2, 3, 4, 5, 6, 7, 8, 9,
  ],
  letters: [
    'A', 'B', 'C', 'D', 'E', 'F', 'X', 'Y', 'Z',
  ],

  securityForegroundClasses: {
    '1.0': 'eve-security-color-10',
    '0.9': 'eve-security-color-09',
    '0.8': 'eve-security-color-08',
    '0.7': 'eve-security-color-07',
    '0.6': 'eve-security-color-06',
    '0.5': 'eve-security-color-05',
    '0.4': 'eve-security-color-04',
    '0.3': 'eve-security-color-03',
    '0.2': 'eve-security-color-02',
    '0.1': 'eve-security-color-01',
    '0.0': 'eve-security-color-00',
    '-0.0': 'eve-security-color-00',
    '-0.1': 'eve-security-color-m-01',
    '-0.2': 'eve-security-color-m-02',
    '-0.3': 'eve-security-color-m-03',
    '-0.4': 'eve-security-color-m-04',
    '-0.5': 'eve-security-color-m-05',
    '-0.6': 'eve-security-color-m-06',
    '-0.7': 'eve-security-color-m-07',
    '-0.8': 'eve-security-color-m-08',
    '-0.9': 'eve-security-color-m-09',
    '-1.0': 'eve-security-color-m-10',
  },

  securityBackgroundClasses: {
    '1.0': 'eve-security-background-10',
    '0.9': 'eve-security-background-09',
    '0.8': 'eve-security-background-08',
    '0.7': 'eve-security-background-07',
    '0.6': 'eve-security-background-06',
    '0.5': 'eve-security-background-05',
    '0.4': 'eve-security-background-04',
    '0.3': 'eve-security-background-03',
    '0.2': 'eve-security-background-02',
    '0.1': 'eve-security-background-01',
    '0.0': 'eve-security-background-00',
    '-0.0': 'eve-security-background-00',
    '-0.1': 'eve-security-background-m-01',
    '-0.2': 'eve-security-background-m-02',
    '-0.3': 'eve-security-background-m-03',
    '-0.4': 'eve-security-background-m-04',
    '-0.5': 'eve-security-background-m-05',
    '-0.6': 'eve-security-background-m-06',
    '-0.7': 'eve-security-background-m-07',
    '-0.8': 'eve-security-background-m-08',
    '-0.9': 'eve-security-background-m-09',
    '-1.0': 'eve-security-background-m-10',
  },

  // typeClasses : {
  //     "C1"  : "eve-wh-type-color-c1",
  //     "C2"  : "eve-wh-type-color-c2",
  //     "C3"  : "eve-wh-type-color-c3",
  //     "C4"  : "eve-wh-type-color-c4",
  //     "C5"  : "eve-wh-type-color-c5",
  //     "C6"  : "eve-wh-type-color-c6",
  //     "C12" : "eve-wh-type-color-thera",
  //     "C13" : "eve-wh-type-color-c13",
  //     "D"   : "eve-wh-type-color-drifter",
  //     "H"   : "eve-wh-type-color-high",
  //     "L"   : "eve-wh-type-color-low",
  //     "N"   : "eve-wh-type-color-null"
  // },

  // typeBackgroundClasses : {
  //     "C1"  : "eve-wh-type-background-c1",
  //     "C2"  : "eve-wh-type-background-c2",
  //     "C3"  : "eve-wh-type-background-c3",
  //     "C4"  : "eve-wh-type-background-c4",
  //     "C5"  : "eve-wh-type-background-c5",
  //     "C6"  : "eve-wh-type-background-c6",
  //     "C12" : "eve-wh-type-background-thera",
  //     "C13" : "eve-wh-type-background-c13",
  //     "D"   : "eve-wh-type-background-drifter",
  //     "H"   : "eve-wh-type-background-high",
  //     "L"   : "eve-wh-type-background-low",
  //     "N"   : "eve-wh-type-background-null"
  // },

  // kindClassed : {
  //     "0" : "eve-kind-color-high",
  //     "1" : "eve-kind-color-low",
  //     "2" : "eve-kind-color-null",
  //     "3" : "eve-kind-color-wh",
  //     "4" : "eve-kind-color-thera",
  //     "5" : "eve-kind-color-abyss",
  //     "6" : "eve-kind-color-penalty",
  //     "7" : "eve-kind-color-pochven",
  // },

  markerBookmarkColorsClasses: {
    shattered: 'wd-marker-bookmark-color-shattered',
    a0: 'wd-marker-bookmark-color-a0',
    activityNormal: 'wd-marker-bookmark-color-normal',
    activityWarn: 'wd-marker-bookmark-color-warn',
    activityDanger: 'wd-marker-bookmark-color-danger',


    average: 'wd-marker-bookmark-color-average',
    ytirium: 'wd-marker-bookmark-color-ytirium',
    l1: 'wd-marker-bookmark-color-l1',
    l2: 'wd-marker-bookmark-color-l2',
    l3: 'wd-marker-bookmark-color-l3',
  },

  /**
   ccp1: -1,
   c1: 1,
   c2: 2,
   c3: 3,
   c4: 4,
   c5: 5,
   c6: 6,
   hs: 7,
   ls: 8,
   ns: 9,
   ccp2: 10,
   ccp3: 11,
   thera: 12,
   c13: 13,
   sentinel: 14,
   baribican: 15,
   vidette: 16,
   conflux: 17,
   redoubt: 18,
   a1: 19,
   a2: 20,
   a3: 21,
   a4: 22,
   a5: 23,
   ccp4: 24,
   pochven: 25,
   zarzakh: 10100,
   */

  systemClassStyles: {
    '-1': '',
    '1': 'eve-kind-color-wh',
    '2': 'eve-kind-color-wh',
    '3': 'eve-kind-color-wh',
    '4': 'eve-kind-color-wh',
    '5': 'eve-kind-color-wh',
    '6': 'eve-kind-color-wh',
    '7': 'eve-kind-color-high',
    '8': 'eve-kind-color-low',
    '9': 'eve-kind-color-null',
    '10': '',
    '11': '',
    '12': 'eve-kind-color-thera',
    '13': 'eve-kind-color-wh',
    '14': 'eve-kind-color-wh',
    '15': 'eve-kind-color-wh',
    '16': 'eve-kind-color-wh',
    '17': 'eve-kind-color-wh',
    '18': 'eve-kind-color-wh',
    '19': 'eve-kind-color-abyss',
    '20': 'eve-kind-color-abyss',
    '21': 'eve-kind-color-abyss',
    '22': 'eve-kind-color-abyss',
    '23': 'eve-kind-color-abyss',
    '24': 'eve-kind-color-penalty',
    '25': 'eve-kind-color-pochven',
    '10100': 'eve-kind-color-zarzakh',
  },

  wormholeClassStyles: {
    '-1': '',
    '1': 'eve-wh-type-color-c1',
    '2': 'eve-wh-type-color-c2',
    '3': 'eve-wh-type-color-c3',
    '4': 'eve-wh-type-color-c4',
    '5': 'eve-wh-type-color-c5',
    '6': 'eve-wh-type-color-c6',
    '7': 'eve-wh-type-color-high',
    '8': 'eve-wh-type-color-low',
    '9': 'eve-wh-type-color-null',
    '10': '',
    '11': '',
    '12': 'eve-wh-type-color-thera',
    '13': 'eve-wh-type-color-c13',
    '14': 'eve-wh-type-color-drifter',
    '15': 'eve-wh-type-color-drifter',
    '16': 'eve-wh-type-color-drifter',
    '17': 'eve-wh-type-color-drifter',
    '18': 'eve-wh-type-color-drifter',
    '19': 'eve-kind-color-abyss',
    '20': 'eve-kind-color-abyss',
    '21': 'eve-kind-color-abyss',
    '22': 'eve-kind-color-abyss',
    '23': 'eve-kind-color-abyss',
    '24': 'eve-kind-color-penalty',
    '25': 'eve-wh-type-color-null',
    '10100': 'eve-wh-type-color-thera',
  },

  systemClassBackgroundStyles: {
    '-1': '',
    '1': 'eve-kind-background-wh',
    '2': 'eve-kind-background-wh',
    '3': 'eve-kind-background-wh',
    '4': 'eve-kind-background-wh',
    '5': 'eve-kind-background-wh',
    '6': 'eve-kind-background-wh',
    '7': 'eve-kind-background-high',
    '8': 'eve-kind-background-low',
    '9': 'eve-kind-background-null',
    '10': '',
    '11': '',
    '12': 'eve-kind-background-thera',
    '13': 'eve-kind-background-wh',
    '14': 'eve-kind-background-wh',
    '15': 'eve-kind-background-wh',
    '16': 'eve-kind-background-wh',
    '17': 'eve-kind-background-wh',
    '18': 'eve-kind-background-wh',
    '19': 'eve-kind-background-abyss',
    '20': 'eve-kind-background-abyss',
    '21': 'eve-kind-background-abyss',
    '22': 'eve-kind-background-abyss',
    '23': 'eve-kind-background-abyss',
    '24': 'eve-kind-background-penalty',
    '25': 'eve-kind-background-pochven',
    '10100': 'eve-kind-background-zarzakh',
  },

  wormholeClassBackgroundStyles: {
    '1': 'eve-wh-type-background-c1',
    '2': 'eve-wh-type-background-c2',
    '3': 'eve-wh-type-background-c3',
    '4': 'eve-wh-type-background-c4',
    '5': 'eve-wh-type-background-c5',
    '6': 'eve-wh-type-background-c6',
    '7': 'eve-wh-type-background-high',
    '8': 'eve-wh-type-background-low',
    '9': 'eve-wh-type-background-null',
    '12': 'eve-wh-type-background-thera',
    '13': 'eve-wh-type-background-c13',
    '14': 'eve-wh-type-background-drifter',
    '15': 'eve-wh-type-background-drifter',
    '16': 'eve-wh-type-background-drifter',
    '17': 'eve-wh-type-background-drifter',
    '18': 'eve-wh-type-background-drifter',
    '25': 'eve-wh-type-background-null',
    '10100': 'eve-wh-type-background-null',
  },

  // kindBackgroundClasses : {
  //     "0" : "eve-kind-background-high",
  //     "1" : "eve-kind-background-low",
  //     "2" : "eve-kind-background-null",
  //     "3" : "eve-kind-background-wh",
  //     "4" : "eve-kind-background-thera",
  //     "5" : "eve-kind-background-abyss",
  //     "6" : "eve-kind-background-penalty",
  //     "7" : "eve-kind-background-pochven",
  // },

  effects: {
    'Pulsar': 'text-eve-wh-effect-color-pulsar',
    'Magnetar': 'text-eve-wh-effect-color-magnetar',
    'Wolf-Rayet Star': 'text-eve-wh-effect-color-wolfRayet',
    'Black Hole': 'text-eve-wh-effect-color-blackHole',
    'Cataclysmic Variable': 'text-eve-wh-effect-color-cataclysmicVariable',
    'Red Giant': 'text-eve-wh-effect-color-redGiant',

    'Dazh Liminality Locus': 'text-eve-wh-effect-color-dazhLiminalityLocus',
    'Imperial Stellar Observatory': 'text-eve-wh-effect-color-imperialStellarObservatory',
    'State Stellar Observatory': 'text-eve-wh-effect-color-stateStellarObservatory',
    'Republic Stellar Observatory': 'text-eve-wh-effect-color-republicStellarObservatory',
    'Federal Stellar Observatory': 'text-eve-wh-effect-color-federalStellarObservatory',
  },

  effectsBackground: {
    'Pulsar': 'eve-wh-effect-color-pulsar',
    'Magnetar': 'eve-wh-effect-color-magnetar',
    'Wolf-Rayet Star': 'eve-wh-effect-color-wolfRayet',
    'Black Hole': 'eve-wh-effect-color-blackHole',
    'Cataclysmic Variable': 'eve-wh-effect-color-cataclysmicVariable',
    'Red Giant': 'eve-wh-effect-color-redGiant',

    'Dazh Liminality Locus': 'eve-wh-effect-color-dazhLiminalityLocus',
    'Imperial Stellar Observatory': 'eve-wh-effect-color-imperialStellarObservatory',
    'State Stellar Observatory': 'eve-wh-effect-color-stateStellarObservatory',
    'Republic Stellar Observatory': 'eve-wh-effect-color-republicStellarObservatory',
    'Federal Stellar Observatory': 'eve-wh-effect-color-federalStellarObservatory',
  },


  statuses: [
    { id: 'unknown', name: 'Clear', icon: 'block' },
    { id: 'home', name: 'Home', icon: 'invert_colors' },
    { id: 'friendly', name: 'Friendly', icon: 'invert_colors' },
    { id: 'lookingFor', name: 'Looking for', icon: 'invert_colors' },
    { id: 'warning', name: 'Warning', icon: 'invert_colors' },
    { id: 'targetPrimary', name: 'Target primary', icon: 'invert_colors' },
    { id: 'targetSecondary', name: 'Target secondary', icon: 'invert_colors' },
    { id: 'dangerousPrimary', name: 'Dangerous primary', icon: 'invert_colors' },
    { id: 'dangerousSecondary', name: 'Dangerous secondary', icon: 'invert_colors' },
  ],

  labels: [
    { id: 'clear',   name: 'Clear',   shortName: '',    icon: '' },
    { id: 'average', name: 'Average', shortName: 'AVG', icon: '' },
    { id: 'ytirium', name: 'Ytirium', shortName: 'YT',  icon: '' },
    { id: 'l1',      name: 'Label 1', shortName: 'L1',  icon: '' },
    { id: 'l2',      name: 'Label 2', shortName: 'L2',  icon: '' },
    { id: 'l3',      name: 'Label 3', shortName: 'L3',  icon: '' },
  ],

  statusesNames: {
    unknown: 0,
    friendly: 1,
    warning: 2,
    targetPrimary: 3,
    targetSecondary: 4,
    dangerousPrimary: 5,
    dangerousSecondary: 6,
    lookingFor: 7,
    home: 8,
  },

  advices: [
    { type: 'joke', name: '', description: 'Sabre on DScan' },

    { type: 'advice', name: '', description: 'Don\'t forget close a K162 before the klac klac' },

    { type: 'mapperHelp', name: '', description: 'You can add yourself, corporations and alliances to your group' },
    { type: 'mapperHelp', name: '', description: 'Don\'t forget check available groups.' },
    { type: 'mapperHelp', name: '', description: 'Available groups - groups to which you have access.' },
    { type: 'mapperHelp', name: '', description: 'You can check route on your map - just mark system as hub.' },
  ],

  timeStatuses: [
    { title: 'Whole', icon: 'done_all', id: 0 },
    { title: 'End of life', icon: 'error_outline', id: 1 },
  ],

  timeStatusesMap: {
    whole: { title: 'Set EOL', icon: 'done_all', id: 0 },
    eol: { title: 'Set whole', icon: 'error_outline', id: 1 },
  },

  massStatuses: [
    { title: 'Whole', icon: 'done', id: 0 },
    { title: 'Less than half', icon: 'trending_down', id: 1 },
    { title: 'Verge of collapse', icon: 'error_outline', id: 2 },
  ],

  shipSizeStatuses: [
    { title: 'Frigate (S)', icon: 'done', id: 0 },
    { title: 'Normal (M/L)', icon: 'trending_down', id: 1 },
    { title: 'Capital (XL)', icon: 'error_outline', id: 2 },
  ],

  dScan: {
    kindNames: {
      cosmicSignature: 'Cosmic Signature',
      cosmicAnomaly: 'Cosmic Anomaly',
      structure: 'Structure',
      starbase: 'Starbase',
      drone: 'Drone',
      deployable: 'Deployable',
      ship: 'Ship',
    },
    kinds: [
      { id: 'Cosmic Signature' },
      { id: 'Cosmic Anomaly' },
    ],
    groups: [
      { id: 'Gas Site' },
      { id: 'Relic Site' },
      { id: 'Data Site' },
      { id: 'Ore Site' },
      { id: 'Combat Site' },
      { id: 'Wormhole' },
      { id: '' },
    ],
    names: [
      { id: '' },
    ],
  },

  signaturesTypes: [
    { id: 'cosmicAnomaly', title: 'Show Anomalies', value: true },
    { id: 'cosmicSignature', title: 'Show Cosmic Signatures', value: true },
    { id: 'deployable', title: 'Show Deployables', value: true },
    { id: 'structure', title: 'Show Structures', value: true },
    { id: 'starbase', title: 'Show Starbase', value: true },
    { id: 'ship', title: 'Show Ships', value: true },
    { id: 'drone', title: 'Show Drones And Charges', value: true },
  ],

  defaultRouteSettings: {
    pathType: 'shortest',
    includeMassCrit: true,
    includeEol: true,
    includeFrig: true,
    includeCruise: true,
    avoidWormholes: false,
    avoidPochven: false,
    avoidEdencom: false,
    avoidTriglavian: false,
    includeThera: true,
  },

  regionShortName: {
    'Aridia': 'Aridia',
    'Black Rise': 'Black Rise',
    'The Bleak Lands': 'Bl. Lands',
    'The Citadel': 'The Citadel',
    'Derelik': 'Derelik',
    'Devoid': 'Devoid',
    'Domain': 'Domain',
    'Essence': 'Essence',
    'Everyshore': 'Everyshore',
    'The Forge': 'The Forge',
    'Genesis': 'Genesis',
    'Heimatar': 'Heimatar',
    'Kador': 'Kador',
    'Khanid': 'Khanid',
    'Kor-Azor': 'Kor-Azor',
    'Lonetrek': 'Lonetrek',
    'Metropolis': 'Metropolis',
    'Molden Heath': 'Molden H.',
    'Placid': 'Placid',
    'Sinq Laison': 'S. Laison',
    'Solitude': 'Solitude',
    'Tash-Murkon': 'Tash-M.',
    'Verge Vendor': 'Verge V.',
    'Branch': 'Branch',
    'Cache': 'Cache',
    'Catch': 'Catch',
    'Cloud Ring': 'Cloud Ring',
    'Cobalt Edge': 'Cobalt E.',
    'Curse': 'Curse',
    'Deklein': 'Deklein',
    'Delve': 'Delve',
    'Detorid': 'Detorid',
    'Esoteria': 'Esoteria',
    'Etherium Reach': 'Etherium R.',
    'Fade': 'Fade',
    'Feythabolis': 'Feythabolis',
    'Fountain': 'Fountain',
    'Geminate': 'Geminate',
    'Great Wildlands': 'G. Wild.',
    'Immensea': 'Immensea',
    'Impass': 'Impass',
    'Insmother': 'Insmother',
    'The Kalevala Expanse': 'Kalevala E.',
    'Malpais': 'Malpais',
    'Oasa': 'Oasa',
    'Omist': 'Omist',
    'Outer Passage': 'O. Passage',
    'Outer Ring': 'Outer Ring',
    'Paragon Soul': 'Paragon S.',
    'Period Basis': 'Period B.',
    'Perrigen Falls': 'Perrigen F.',
    'Pochven': 'Pochven',
    'Providence': 'Providence',
    'Pure Blind': 'Pure Blind',
    'Querious': 'Querious',
    'Scalding Pass': 'Scalding P.',
    'The Spire': 'The Spire',
    'Stain': 'Stain',
    'Syndicate': 'Syndicate',
    'Tenal': 'Tenal',
    'Tenerifis': 'Tenerifis',
    'Tribute': 'Tribute',
    'Vale of the Silent': 'V. Silent',
    'Venal': 'Venal',
    'Wicked Creek': 'Wicked C.',
  },

  sunTypes: {
    'a0': 3801,
  },

  activityTypeIds: [
    'activityNormal',
    'activityWarn',
    'activityDanger',
  ],
};